# Generated by Django 5.1.3 on 2024-11-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('descriotion', models.TextField()),
                ('start_data', models.DateField()),
                ('end_data', models.DateField()),
                ('max_students', models.PositiveIntegerField()),
            ],
        ),
    ]
